# Generated by Django 4.1.3 on 2022-12-08 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
            ],
        ),
    ]
